<?php
/*
Author: Cesar Caballero Gallego
Date: 01/03/2012 - 15:21:59
File: statusList.php
*/
?>

			<h2>Mostrar:</h2>
			<ul>
				<li><?php echo Html::linkAction('index','Todos') ?></li>
				<li><?php echo Html::linkAction('group/admin','Administradores') ?></li>
				<li><?php echo Html::linkAction('group/editor','Editores') ?></li>	
				<li><?php echo Html::linkAction('group/user','Usuarios') ?></li>
			</ul>