<?php
/*
Creado por: Phillipo
Fecha: 25/05/2012 16:59:36
Fichero: edit.phtml
*/
?>

	
			<div id="main" class="pages">
			
				<!-- OPTIONS -->
				<div class="sheet-options row-fluid span12">
				
					<div class="span6">
						<h1>Editar página</h1>
					</div>
				
					<!-- 
					<div class="span6 textRight">
						<div class="btn-group">
							<?php echo Html::linkAction('copy','Duplicar','id="copy-'.$page->id.'" title="Crear un contenido igual" class="ui-copyIt btn"') ?>
							<?php echo Html::linkAction('move','Mover','id="move-'.$page->id.'" title="Mover el contenido a otra categoria" class="ui-moveIt btn"') ?>
							<?php echo Html::linkAction('delete','Borrar','id="remove-'.$page->id.'" title="Eliminar este contenido" class="ui-removeIt btn danger"') ?>
						</div>
						
						<div class="btn-group">
							<?php echo Html::linkAction('#','Guardar','id="save-'.$page->id.'" title="Crear un contenido igual" class="ui-saveIt btn"') ?>
							<?php echo Html::linkAction('index','Salir','title="Mover el contenido a otra categoria" class="ui-moveIt btn"') ?>
						</div>							
					</div>
					 -->
					
				</div>	
				<!-- fOPTIONS -->	
				
				<div class="clearfix"><!-- BR --></div>	
			
				<!-- BREADCRUMB -->
				<?php echo View::partial('admin/breadcrumb')?>
				<!-- fBREADCRUMB -->			
			
				<?php echo Form::open('admin/page/edit/'.$page->id.'/'.base64_encode($referer),'post').EOL ?>
				<?php echo Form::hidden('page.page_language_id','','1').EOL ?>
				<?php echo Form::hidden('page.page_sort_order','', $page->page_sort_order).EOL ?>	
				
				<?php View::content() ?>
			
				<!-- TABS -->
				<div class="tabbable tabs-left">
				
					<!-- CONTROLS TABS -->
					<ul class="nav nav-tabs">
						<li class="active"><a href="#ui-content-content" data-toggle="tab">Propiedades</a></li>
						<li><a href="#ui-content-settings" data-toggle="tab">Propiedades avanzadas</a></li>
						<li><a href="#ui-content-seo" data-toggle="tab">SEO</a></li>			
						<li><a href="#ui-content-users" data-toggle="tab">Permisos de acceso</a></li>						
						<li><a href="#ui-content-history" data-toggle="tab">Historial de cambios</a></li>
					</ul>			
					<!-- fCONTROLS TABS -->
					
					<!-- CONTENT TABS -->
					<div class="tab-content">
						
						<!-- PESTAÑA GENERAL -->
						<div id="ui-content-content" class="tab-pane active">
											
							<fieldset><legend>Datos generales</legend>
						
								<div class="frow">
								<label for="attributes_title">Título <span class="help-inline">( Título a mostrar como cabecera de página )</span></label>
								<?php echo Form::text('attributes.title','class="span12 ui-slug"',$attributes->title).EOL ?>
								</div>
								
								<div class="frow">
								Enlace permanente: http://www.direccióndelblog.com/<span class="ui-slug-result"><?php echo $page->page_slug ?></span>
								<?php echo Form::hidden('page.page_slug','class="ui-slug-result"',$page->page_slug).EOL ?>
								</div>
							
							</fieldset>
							
							<fieldset><legend>Opciones de menú</legend>
						
								<div class="frow">
								<label for="attributes_title">Título de menú<span class="help-inline">( Título a mostrar como menú )</span></label>
								<?php echo Form::text('attributes.short_title','class="span12"',$attributes->short_title).EOL ?>
								</div>
								
								<div class="frow">
									<label for="attributes_title">Elemento superior<span class="help-inline"></span></label>
									<?php
									$listado = new pageSelect();
									echo $listado->show('page.page_parent_id',$key = '.'); 
									?>
								</div>
							
							</fieldset>
							
							
							
							<fieldset><legend>Tipo</legend>
							
								<div class="controls">
																				
									<label class="radio" for="attributes_redirect_type0">
									<?php echo Form::radio('page.page_redirect', 'none', 'class="redirectChecker"', ($page->page_redirect == 'none' ? true : false)).EOL ?>
									Plantilla
									</label>
									
									<label class="radio" for="attributes_redirect_type1">
									<?php echo Form::radio('page.page_redirect', 'internal', 'class="redirectChecker"', ($page->page_redirect == 'internal' ? true : false)).EOL ?>
									Redirección interna
									</label>
		
									<label class="radio" for="attributes_redirect_type2">
									<?php echo Form::radio('page.page_redirect', 'external', 'class="redirectChecker"', ($page->page_redirect == 'external' ? true : false)).EOL ?>
									Redirección externa
									</label>									
														
								</div>
												
							</fieldset>
							
							<fieldset id="ui-redirect-external"><legend>Redirección externa</legend>
								<label for="attributes_redirect_external">Dirección web <span>http://www.dominio.com/</span></label>
								<?php echo Form::text('attributes.redirect_external','class="span12"', $attributes->redirect_external).EOL ?>
							</fieldset>
			
							<fieldset id="ui-redirect-internal"><legend>Redirección interna</legend>
								<label for="attributes_redirect_internal">Páginas disponibles</label>
								<?php //echo Form::text('attributes.redirect_internal','class="span12"','desplagable!!!').EOL ?>

									<?php
									$listado = new pageSelect();
									echo $listado->show('attributes.redirect_internal', $attributes->redirect_internal, $key = '.'); 
									?>			
								
								
							</fieldset>
							
							<fieldset id="ui-redirect-none"><legend>Plantilla</legend>
							
								<div id="templateCarousel">									
									<div class="viewport">
										 <ul class="overview">								

							<?php
							$n = 0;
							foreach ($templateList as $template) {
 								echo '		<li>';
								echo '			<label for="page_template_id'.$n.'" class="radio">'.Form::radio('page.page_template_id', $template->template_id,null, ($template->template_id == $page->page_template_id ? true : false) ).'Seleccionar</label>';
								echo Html::img('template/'.$template->template_preview);
 								echo '		</li>';
								$n++;								
							}	
							?>						
										</ul>	
									</div>
									<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>									
								</div>			
							
							
							</fieldset>
							
						</div>	
						<!-- fPESTAÑA GENERAL -->
						
						<div class="clearfix"><!-- BR --></div>				
									
						<!-- PESTAÑA SEO -->
						<div id="ui-content-seo" class="tab-pane">	
						
							<fieldset><legend>Información para buscadores (Google, Yahoo, Terra, Ask...)</legend>
							
								<div class="frow">
									<label for="attributes_seotitle">Titulo SEO</label>
									<?php echo Form::text('attributes.seotitle','class="span12"', $attributes->seotitle).EOL ?>
								</div>
								
								<div class="frow">
									<label for="attributes_seodesc">Descripción SEO <span id="attributes_seodescLimit" class="help-inline"> ( <?php echo strlen($attributes->seodesc)?> / 255 caracteres)</span></label>
									<?php echo Form::textarea('attributes.seodesc','class="span12 ui-limited limit200"', $attributes->seodesc).EOL ?>
								</div>
								
								<div class="frow">
									<label for="attributes_seotags">Etiquetas SEO<span class="help-inline">( palabra1, palabra2, frase1, frase2 )</span></label>
									<?php echo Form::text('attributes.seotags','class="span12"', $attributes->seotags).EOL ?>
								</div>
							
							</fieldset>
							
						</div>
						<!-- fPESTAÑA SEO -->
						
						<div class="clearfix"><!-- BR --></div>			
						
						<!-- PESTAÑA PROPIEDADES -->
						<div id="ui-content-settings" class="tab-pane">					
							
							<fieldset><legend>Visibilidad</legend>
							
								<div class="controls">
								
									<label for="page_page_status0" class="radio">
									<?php echo Form::radio('page.page_status', 'public', '', ($page->page_status == 'public' ? true : false)).EOL ?>
									Publicado
									</label>
		
									<label for="page_page_status1" class="radio">
									<?php echo Form::radio('page.page_status', 'private', '', ($page->page_status == 'private' ? true : false)).EOL ?>
									Privado
									</label>					
		
									<label for="page_page_status2" class="radio">				
									<?php echo Form::radio('page.page_status', 'draft', '', ($page->page_status == 'draft' ? true : false)).EOL ?>
									Borrador
									</label>
									
								</div>	
												
							</fieldset>	
							
							<fieldset><legend>Fechas publicación</legend>
							
								<div class="row-fluid">
									<div class="span2">
										<label for="page_page_publish_up">Inicio</label>
										<?php echo Form::text('page.page_publish_up','class="span12 ui-datePicker"', Innocms::humanDate($page->page_publish_up,'d-m-Y H:i:s')).EOL ?>
									</div>				
									<div class="span2">				
										<label for="page_page_publish_down">Fin</label>
										<?php echo Form::text('page.page_publish_down','class="span12 ui-datePicker"', Innocms::humandate($page->page_publish_down,'d-m-Y H:i:s')).EOL ?>
									</div>		
								</div>
								
								<div class="clearfix"><!-- BR --></div>
				
								<div class="frow">
									<label for="page_page_publish_expires" class="checkbox">
									<?php echo Form::check('page.page_publish_expires', '1', '', $page->page_publish_expires).EOL ?>
									Ocultar al coincidir con la fecha fin
									</label>
								</div>				
				
							</fieldset>					
												
						</div>					
						<!-- fPESTAÑA PROPIEDADES -->				
						
						<div class="clearfix"><!-- BR --></div>
						
						<!-- PESTAÑA USUARIOS -->
						<div id="ui-content-users" class="tab-pane">
						
							<fieldset><legend>Selecciona un grupo</legend>
							
							
							
							</fieldset>
						
						</div>
						
						
						<!-- fPESTAÑA USUARIOS -->
						
						
						<div class="clearfix"><!-- BR --></div>				
						
						<!-- PESTAÑA HISTORIAL -->
						<div id="ui-content-history" class="tab-pane">
							
							<fieldset>
							<legend>Historial de modificaciones</legend>
							
							<div class="frow">
							<label for="created_at">Creado:</label>			
							<?php echo Form::text('created_at','class="noneditable" readonly="readonly"', Innocms::humanDate($page->page_created_at)); ?>
							</div>
							<div class="frow">
							<label for="modified_in">Modificado:</label>
							<?php echo Form::text('modified_in','class="noneditable" readonly="readonly"', Innocms::humanDate($page->page_modified_in)); ?>
							</div>
							</fieldset>
						
						</div>
						<!-- fPESTAÑA HISTORIAL -->
				
					</div>
					<!-- fCONTENT TAG -->
				
				</div>
				<!-- fTABS -->

				<!-- ACTIONS -->
				<div class="form-actions well">

					<div class="span6">
						<?php echo Html::link($referer,'Descartar','class="btn btn-danger"') ?>
					</div>
					<div class="span6">
						<div class="btn-group pull-right">
							<input type="submit" value="Guardar datos" class="btn btn-primary" />
							<input type="button" value="Vista previa" class="btn" />							
						</div>
					</div>
					
				</div>
				<!-- fACTIONS -->	
		
				<?php echo Form::close() ?>	
				
			</div>
		
		
