<?php
/*
Creado por: Phillipo
Fecha: 25/05/2011 16:59:36
Fichero: admin_controller.php
*/
?>

			<div id="main" class="pages">
			
				<h1>Páginas</h1>
				
				<!-- BREADCRUMB -->
				<?php echo View::partial('admin/breadcrumb')?>
				<!-- fBREADCRUMB -->			
				
				<?php View::content() ?>
					
				<!-- Opciones listado -->
				<?php echo View::partial('admin/optionsLists',0,array('searchTerm'=>$searchTerm)) ?>
				<!-- fOpciones listado -->
				
				<div class="clearfix"><!-- BR --></div>	
					
				<?php if (sizeof($contentList) > 0 ) { ?>		
				
				<?php echo Form::open('','post','id="ui-form"'); ?>
				
				<table id="pageList" class="table table-striped">
				<thead>
				<tr>
					<th><?php echo Form::check('ui-checkAll','1','class="ui-checkAll" title="Seleccionar/deseleccionar todos"',false)?></th>
					<th>Titulo</th>
					<th>Última modificación</th>
					<th>ID</th>
				</tr>
				</thead>
				<tbody>
				<?php
				foreach ($contentList as $item) { 
					$date = Innocms::humanDate($item->page_modified_in,'d/m/Y H:i:s');
				?>
					<tr>
					<td><input type="checkbox" id="<?php echo 'listID-'.$item->page_id ?>" name="listID[]" value="<?php echo $item->page_id ?>" title="Seleccionar / deseleccionar"></td>
					<td><?php echo Html::linkAction('edit/'.$item->page_id.'/'.Innocms::refererEncode(), $item->page_attribute_value) ?></td>
					<td><?php echo ($date == '01/01/1970 01:00:00' ? 'Nunca' : $date)  ?></td>	
					<td><?php echo $item->page_id ?></td>
					</tr>
				<?php } ?>
				</tbody>
				</table>
				
				<?php } else { ?>
				
					<p>No hay páginas según criterios o búsqueda.</p>
					
				<?php } ?>	
				
			</div>