<?php
/*
Author: Cesar Caballero Gallego
Date: 07/02/2012 - 20:34:48
File: createItems.phtml
*/
?>


			<div class="btn-group">
				<a class="btn btn-primary" href="#">
					<i class="icon-plus icon-white"></i>&nbsp;&nbsp;&nbsp;&nbsp;Crear...</a> 
					<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<li><a href="/admin/page/create"><i class="icon-pencil"></i>&nbsp;&nbsp;Página</a></li>
					<li><a href="/admin/module/create"><i class="icon-pencil"></i>&nbsp;&nbsp;Modulos</a></li>
					<li><a href="/admin/menu/create"><i class="icon-pencil"></i>&nbsp;&nbsp;Menú</a></li>
					<li class="divider"></li>
					<li><a href="#"><i class="icon-ban-circle"></i> Páginas</a></li>
				</ul>
			</div>