<?php
/*
Creado por: Phillipo
Fecha: 01/07/2011 21:33:38
Fichero: index.phtml
*/

?>

<div id="content">

	<div id="main">
	
		<h1>Listado de categorias</h1>
	
		<ul id="ui-categoryTree" class="treeview-red">
		<li><span>Item 1</span>
			<ul>
				<li><span>Item 1.0</span>
					<ul>
						<li><span>Item 1.0.0</span></li>
					</ul>
				</li>
				<li><span>Item 1.1</span></li>
				<li><span>Item 1.2</span>
					<ul>
						<li><span>Item 1.2.0</span>
						<ul>
							<li><span>Item 1.2.0.0</span></li>
							<li><span>Item 1.2.0.1</span></li>
							<li><span>Item 1.2.0.2</span></li>
						</ul>
					</li>
						<li><span>Item 1.2.1</span>
						<ul>
							<li><span>Item 1.2.1.0</span></li>
						</ul>
					</li>
						<li><span>Item 1.2.2</span>
						<ul>
							<li><span>Item 1.2.2.0</span></li>
							<li><span>Item 1.2.2.1</span></li>
							<li><span>Item 1.2.2.2</span></li>
						</ul>
					</li>
					</ul>
				</li>
			</ul>
		</li>
		<li><span>Item 2</span>
			<ul>
				<li><span>Item 2.0</span>
					<ul>
						<li><span>Item 2.0.0</span>
						<ul>
							<li><span>Item 2.0.0.0</span></li>
							<li><span>Item 2.0.0.1</span></li>
						</ul>
					</li>
					</ul>
				</li>
				<li><span>Item 2.1</span>
					<ul>
						<li><span>Item 2.1.0</span>
						<ul>
							<li><span>Item 2.1.0.0</span></li>
						</ul>
					</li>
						<li><span>Item 2.1.1</span>
						<ul>
							<li><span>Item 2.1.1.0</span></li>
							<li><span>Item 2.1.1.1</span></li>
							<li><span>Item 2.1.1.2</span></li>
						</ul>
					</li>
						<li><span>Item 2.1.2</span>
						<ul>
							<li><span>Item 2.1.2.0</span></li>
							<li><span>Item 2.1.2.1</span></li>
							<li><span>Item 2.1.2.2</span></li>
						</ul>
					</li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="open"><span>Item 3</span>
			<ul>
				<li class="open"><span>Item 3.0</span>
					<ul>
						<li><span>Item 3.0.0</span></li>
						<li><span>Item 3.0.1</span>
						<ul>
							<li><span>Item 3.0.1.0</span></li>
							<li><span>Item 3.0.1.1</span></li>
						</ul>
						
					</li>
						<li><span>Item 3.0.2</span>
						<ul>
							<li><span>Item 3.0.2.0</span></li>
							<li><span>Item 3.0.2.1</span></li>
							<li><span>Item 3.0.2.2</span></li>
						</ul>
					</li>
					</ul>
				</li>
			</ul>
		</li>
		</ul>

	
	
	
	</div>


</div>