<?php
/*
Author: Cesar Caballero Gallego
Date: 07/02/2012 - 20:34:48
File: createItems.phtml
*/
?>


			<div class="btn-group">
				<a class="btn btn-primary" href="#">
					<i class="icon-plus icon-white"></i>&nbsp;&nbsp;&nbsp;&nbsp;Crear contenido</a> 
					<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu">
					<li><a href="/admin/content/create"><i class="icon-pencil"></i> Genérico</a></li>
					<li><a href="/admin/content/create"><i class="icon-pencil"></i> Producto</a></li>
					<li><a href="/admin/content/create"><i class="icon-pencil"></i> Entrada blog</a></li>
					<li class="divider"></li>
					<li><a href="/admin/category/create"><i class="icon-trash"></i> Categoria</a></li>					
					<li><a href="/admin/page/create"><i class="icon-ban-circle"></i> Página</a></li>
				</ul>
			</div>