<?php echo View::partial('admin/html_header',0,array('prefs'=>$prefs)).EOL ?>
<body id="adminLayout">
	
	<div class="container">	
		
		<!-- NAVBAR -->
		<div class="navbar">
			<?php echo View::partial('admin/navbar',0,array('prefs'=>$prefs)).EOL ?>
		</div>	
		<div class="clearfix"><!-- BR --></div>	
		<!-- fNAVBAR -->	

		<!-- CONTENT -->	
		<div class="row-fluid">

			<?php if (Router::get('action') == 'index') { ?>
			<!-- LATERAL MENU -->	
			<div id="menubar" class="span3">
				<?php 
						echo View::partial('admin/'.Router::get('controller').'/createItems').EOL;
						echo '<hr >';					
						echo View::partial('admin/'.Router::get('controller').'/statusList', 0, array('categoryList'=>$categoryList)).EOL;
				?>
			</div>
			<!-- fLATERAL MENU -->
			<?php }	?>
		
		
			<!-- VIEW -->
			<div id="content" class="span9">
				
			<?php echo View::content(); ?>
			
			</div>
			<!-- fVIEW -->
				
		</div>		
	
		<!-- fCONTENT -->
	
	</div>
		
</body>
</html>
