<?php echo View::partial('admin/html_header',0,array('prefs'=>$prefs)).EOL ?>
<body id="adminLayout">
		
	<div class="container">	
		
		<!-- NAVBAR -->
		<div class="navbar">
			<?php echo View::partial('admin/navbar',0,array('prefs'=>$prefs)).EOL ?>
		</div>	
		<div class="clear"><!-- BR --></div>	
		<!-- fNAVBAR -->	
	
		<!-- CONTENT -->
		<div class="row-fluid">
	
			<!-- LATERAL MENU -->	
			<div id="menubar" class="span3">
			</div>
			<!-- fLATERAL MENU -->
		
		
			<!-- VIEW -->
			<div id="content" class="span9">	
			<?php echo View::content(); ?>
			</div>
			<!-- fVIEW -->		
		
		</div>
		<!-- fCONTENT -->

	</div>	
		
</body>
</html>
