<?php
/*
Author: Cesar Caballero Gallego
Date: 28/05/2012 - 17:47:57
File: addUser.phtml
*/
?>


				<div class="btn-group">
					<a class="ui-infoUser btn btn-mini" id="<?php echo 'infoUser-'.$user->id ?>" href="#"><?php echo $user->user_name ?></a>
					<a class="ui-removeUser btn btn-mini btn-danger" id="<?php echo 'removeUser-'.$user->id ?>" href="#" title="Quitar elemento de la lista"><i class="icon-remove">&nbsp;</i></a>	
				</div>