<?php
/*
Author: Cesar Caballero Gallego
Date: 23/02/2012 - 13:27:47
File: home1.phtml
*/
?>

							<h1><?php echo $prefs->preferences_title ?></h1>

							<div class="row">
								<div class="span12">
									<section class="row show-grid">
											<div class="span4 editable" id="idZone-1"></div>
											<div class="span4 editable" id="idZone-2"></div>
											<div class="span4 editable" id="idZone-3"></div>
									</section>
								</div>
							</div>
							<div class="clearfix">&nbsp;</div>
							<div class="row">	
								<div class="span12">
									<section class="row">
											<div class="span8 editable"></div>
											<div class="span4 editable"></div>
									</section>
								</div>								
							</div>		
							<div class="clearfix">&nbsp;</div>
							<div class="row">	
								<div class="span12">
									<section class="row">
											<div class="span12 editable"></div>
									</section>
								</div>								
							</div>		
							<div class="clearfix">&nbsp;</div>
							<div class="row">	
								<div class="span12">
									<section class="row">
											<div class="span4 editable"></div>
											<div class="span8 editable"></div>
									</section>
								</div>								
							</div>									
			
