<?php
/*
Author: Cesar Caballero Gallego
Date: 23/02/2012 - 13:27:47
File: home1.phtml
*/
?>

							<div id="ui-preview-template-<?php echo $template->id ?>" class="ui-preview-template">
								<div class="row-fluid">
								<div class="col_9 empty" style="height: 250px"><p><a href="#" class="button icon add">Cabecera</a></p></div>
								</div>
								<div class="clear"></div>
								<div class="row-fluid">					
								<div class="col_3 empty" style="height: 100px"><p><a href="#" class="button icon add">Columna</a></p></div>							
								<div class="col_6 empty" style="height: 100px"><p><a href="#" class="button icon add">Columna</a></p></div>
								</div>
								<div class="clear"><!-- BR --></div>	
							</div>